### ISSUE TITLE
Add a service that reads the work type configuration to determine what attributes are available

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#1057]
Leveraging the logic from the ['validate work_type configuration' feature spec](https://github.com/ndlib/sipity/blob/55e051b92b252a0c2ce56ea9e638fbb4dec347fa/spec/features/sipity/validate_work_type_configuration_spec.rb#L46), it would be helpful to see what all attributes are available for a given work.

Below is logic I used in that spec to find all of the attributes that could be on the given work.

``` ruby
attribute_names = actions.map do |action|
  form = Sipity::Forms::WorkSubmissions.find_the_form(work_area: work_area, processing_action_name: action)
  form.respond_to?(:attribute_names) ? form.attribute_names : []
end.flatten.uniq.map(&:to_s)

(Sipity::Models::AdditionalAttribute.keys.keys & attribute_names).sort
```

**Comment by danhorst** [comment]
Would this be a function on `Sipity::Models::Work`?

**Comment by jeremyf** [comment]
If it is it will be through the composition of a service type object.

Jeremy Friesen
