### ISSUE TITLE
Validation for multi-value

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#223]
Presently we are making a naive assumption about our validations. The presence validator will return unexpected results when given the following:

```ruby
class Book
  attr_accessor :authors
  validates :authors, presence: true
end

book = Book.new
book.authors = [""]
expect(book.valid?).to be_falsey
```

Because the input array is present, though its elements are not.

See [Hydra::Validations](https://github.com/projecthydra-labs/hydra-validations)

**Comment by rbalekai** [comment]
@jeremyf, I have a question

Are these assumptions correct?

book.authors = [ 'Matt Wynne', '   ' ]
expect(book.valid?).to be_falsey

book.authors = [ 'Matt Wynne', nil ]
expect(book.valid?).to be_falsey

book.authors = [ 'Matt Wynne', 'Aslak Hellesoy' ]
expect(book.valid?).to be_truthy
