### ISSUE TITLE
Funny Field Form Placement with Flexbox in Firefox

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#249]
That's good alliteration.  But in Firefox, the Publishing Plans box and Completed Submission box stay in horizontal plane with the Title and Type boxes instead of being in vertical alignment.
![firefox_flexbox issue](https://cloud.githubusercontent.com/assets/6973150/6562488/f8c0a390-c66f-11e4-9fad-b3767abbac68.jpg)

**Comment by danhorst** [comment]
Refine styles with [guidance from Chris Wright](http://www.chriswrightdesign.com/experiments/using-flexbox-today/).

**Comment by danhorst** [comment]
This works fine in current versions of Firefox thanks to [autoprefixer](https://github.com/postcss/autoprefixer).
