### ISSUE TITLE
Incoroporate PID Minter for Production and Pre-Production

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#256]
At present, the PID minter is defined:

```ruby
def default_pid_minter
  -> { SecureRandom.urlsafe_base64(nil, true) }
end
```

[See source](https://github.com/ndlib/sipity/blob/7d31891709e84ab5a319a756542c0addf2233ee3/app/repositories/sipity/commands/work_commands.rb#L117-L120)

Instead the PID minter should be configured in the application and can be overridden in each environment, much like [#default_netid_remote_validator ](https://github.com/ndlib/sipity/blob/7d31891709e84ab5a319a756542c0addf2233ee3/config/application.rb#L26-L29)

**Comment by danhorst** [comment]
@dbrower says that we need to check to see if the appropriate port for the pid service is open in CurateND

**Comment by dbrower** [comment]
It is port 13001, and it is open.

**Comment by dbrower** [comment]
Look at how curate_nd does it. Use ndlib/noids_client.
