### ISSUE TITLE
Create an advisor review page

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#259]
``` console
As an advisor
I want to be able to see the information relevant to my approval
So that I am not bogged down in all kinds of information
```

During the approval process, an advisor cares about the following information:
- The files that have been uploaded
- The associated access rights for each of the files
- The copyright assertion for the uploaded work
- The names and contact information for each of the collaborators

**Comment by danhorst** [comment]
Taking this for mockup generation

**Comment by danhorst** [comment]
A reviewer is concerned with verifying the following:
- The title
- The abstract
- The manuscript (and perhaps other accompanying files)
- The access controls
- The copyright release

**Comment by danhorst** [comment]
![advisor-review](https://cloud.githubusercontent.com/assets/2133/6620439/17ddd778-c8a7-11e4-9148-e39fe794320d.png)
[Mockup HTML](https://notredame.box.com/s/jq3eqsw7lugv8y0midjya6uqp9zj3t4r)

**Comment by cdeluca495** [comment]
:+1:

**Comment by danhorst** [comment]
# Revised Mock-up
![advisor-review-v2](https://cloud.githubusercontent.com/assets/2133/6639659/c4926932-c967-11e4-819e-027d3252850b.png)
[Revised Mockup HTML](https://notredame.box.com/s/socftwc1tbh0r7cvbr0tiigjseymvoa6)

**Comment by jeremyf** [comment]
@danhorst Is this something that we need to have done for 2nd Wave? Is what we have adequate?
