### ISSUE TITLE
Configure/Verify Pre Prod, Prod and Staging to use S3 for Dragonfly storage

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#268]
File attachment managment:
- **Staging:** leave it as the filesystem; update the capistrano task to persist across deployments (if that is still pending)
- **Pre-production & Production**: configure [Dragonfly::S3DataStore](https://github.com/markevans/dragonfly-s3_data_store) using provided S3 keys (via Figaro)

**Comment by danhorst** [comment]
We won't be storing attachments in S3 in development so we will need a way of swapping storage drivers based on the environment.

**Comment by jeremyf** [comment]
The configuration of Dragonfly is here:
https://github.com/ndlib/sipity/blob/28f8d2f8b7b053210b966a70dc380608b5734f46/config/initializers/dragonfly.rb#L11-L18
