### ISSUE TITLE
Check for YAML parse errors

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#290]
We bypass I18n in the test suite to speed things up but we depend on it a lot for the application. This is ordinarily fine but introduces some risk.

For example 78cb09d5fe52692590e5608da600a72f414e309c introduced a syntax error into the YAML file but it did not cause any tests or validations to fail. This kept the build passing but the application could no longer render any pages.

**Comment by jeremyf** [comment]
I believe that we want to add another task to the default tests that is `validate_translations` or some such thing.
