### ISSUE TITLE
Allow “rich text” for some attributes

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#309]
The following fields should be able to support additional formatting:
- Title
- Alternate Title
- Abstract

The editing interface should support:
- Paragraphs
- Bold
- Italic
- Superscript
- Subscript
- Links
- Linking for URL literals

There may also be a need for:
- Lists
- Uppercase and lowercase greek characters (as UTF-8 symbols)
- Mathematical symbols (as UTF-8 symbols)
- Punctuation (as UTF-8 symbols)

Each “rich text” control must be able to preview how the content will render before the form is submitted.

The HTML rendering of the “rich text” needs to be sanitized of any harmful HTML tags.

There are previous implementations of “rich text” controls in:
- CurateND (rendering but no field controls or preview)
- XUR (rendering, field controls and preview; aging implementation)

**Comment by danhorst** [comment]
Markup “toolbar” options
- [Pen](https://github.com/sofish/pen) looks interesting but would need some, perhaps extensive, customization to support our necessairy features.
- [MarkItUp](https://github.com/markitup/1.x) is customizable and fairly lightweight. Unfortunately it does not appear to be actively maintained. It is the toolbar used in XUR.
- [MeltDown](https://github.com/iphands/Meltdown) looks like a more modern version of MarkItUp

**Comment by jeremyf** [comment]
Lets see about using Redactor http://imperavi.com/redactor/

It is used and purchased by the WSE. Talk to @jonhartzler about this.
