### ISSUE TITLE
Render “feedback” comments on work show page

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#313]
When an advisor, or the graduate school reviewer, leaves a comment it needs to be rendered on the page so that the depositor can see it. (We’re assuming that simply including the comment in an email is insufficient to communicate the feedback.)

**Comment by danhorst** [comment]
Mock-up coming soon.

**Comment by jeremyf** [comment]
@danhorst Given that there are multiple comments possible, what should we do about rendering these? Will it be lots and lots? What about dismissal of these comments?

**Comment by danhorst** [comment]
@jeremyf I am working under the assumption that there is one comment per reviewer per review cycle. I expect the number of comments to be 1–3. They can be rendered in a stack.

As far as dismissing them goes I left it off the mockup for two reasons:
- I expect the comments to be displayed until the work is resubmitted. If we need a way to dismiss comments _during_ the re-submission process another comment state or attribute must be made or else the comments will reappear every time you visit the work show view.
- The focus of the re-submission process is the content of the comment.

Implicit in these comments is the idea that comments are only displayed when they are relevant to the _most recent_ submission.

Am I missing anything?
