### ISSUE TITLE
Email refinements: missing depositor name, move depositor to cc on advisor notice

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#336]
![email-refinements-missing-name](https://cloud.githubusercontent.com/assets/2133/6688240/3a662978-cc88-11e4-9375-55f3632708b7.png)

**Comment by banurekha** [comment]
After investigating more.. Creator names are nil due to bug #423 
Email is sent to user who are 'etd_reviewer', 'advisor' and in development creators and reviewer are same.. So I believe no code changes is necessary for this issue. @danhorst please comment back or we could close this issue.

**Comment by jeremyf** [comment]
This is two issues. The first, `nil` creator names is resolved via #423. The second is related to #455.

**Comment by jeremyf** [comment]
@banurekha Do you want to handle the CC aspect? With #455 you should have what you need to make those changes.

**Comment by banurekha** [comment]
I will add depositor/creating_user email to cc. Although this issue about creating user is added to to_email but it is not, in this case reviewer and creating_user are same
