### ISSUE TITLE
Scope comments on the show view

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#362]
Only show “active” comments on the work show page. Active comments come from the _immediately preceding_ state.

## Work with “active” comments
![362-work-with-active-comments](https://cloud.githubusercontent.com/assets/2133/6716626/26156ede-cd7d-11e4-9fcf-50d1bdc21fa6.png)

## Work with past comment but no “active” comments
![362-work-with-past-comments](https://cloud.githubusercontent.com/assets/2133/6716627/261bec00-cd7d-11e4-8555-65034eb16433.png)

[Mockup HTML](https://notredame.box.com/s/7e42rpftzq1o9pzvihrph1j1l39zfe9z) **NOTE** There are inline comments in the HTML for clarification.

**Comment by jeremyf** [comment]
I'm not planning on adding the below text; The student will respond with a comment and that comment will be displayed. As we look towards a possible more complicated system (i.e. change this predicate, resolve this predicate) we may have something like this.

```
All feedback requests have been resolved
```

**Comment by jeremyf** [comment]
As @rbalekai and I have worked on this, we are not able to act on this `"Active comments
 come from the immediately preceding state."` Instead we are able to `find all comments that were written as part of any action that can transition the entity to its current state`.
