### ISSUE TITLE
The difference between works and files in the access controls listing is unclear

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#410]
The item (work) should be distinguished from attachments.
![410-emphasize-work-difference](https://cloud.githubusercontent.com/assets/2133/6964381/a00b27ca-d916-11e4-9d22-7c02a6e4ddd2.png)

[Source files](https://notredame.box.com/s/85swv7qhecg5yrqop740mte27gibe8kj) (assumes you have the application available at http://localhost:3000)

There are a few tasks packed into this singular issue.

a) Add a "type" column to the Access Policy form page
b) Add emphasis to the "work" type row
c) Better associate manuscript selection; Not certain what the above screenshot means (@danhorst?)
d) Improve long filename wrapping

**Comment by jeremyf** [comment]
Amend the above issue with the following:

> There are a few tasks packed into this singular issue.
> 
> a) Add a "type" column to the Access Policy form page
> b) Add emphasis to the "work" type row
> c) Better associate manuscript selection; Not certain what the above screenshot means (@danhorst?)
> d) Improve long filename wrapping

**Comment by jeremyf** [comment]
@danhorst I'm pushing up the branch `410-The-difference-between-works-and-files-in-the-access-controls-listing-is-unclear` it resolves `a` and part of `b`

I'd like guidance on how to better resolve `b`.

Regarding `c`, I'm not certain what your hint means. And then `d` is something I believe we can hammer out rather quickly if you sit down with me.

**Comment by jeremyf** [comment]
Won't fix item `C` at this point. @danhorst if you want to create a new issue for that, go for it.
