### ISSUE TITLE
Update label for Search Terms

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#411]
![411-search-terms-label](https://cloud.githubusercontent.com/assets/2133/6903921/65e88592-d6eb-11e4-8260-67d6011b9c54.png)

How about this instead: ~~“Please add _keywords_ for this work. ”~~
“Please provide additional _search terms_ for your item”

**Comment by danhorst** [comment]
@cdeluca495 what would you suggest for the text here?

**Comment by cdeluca495** [comment]
Keeping it more generic, here are a few potential options that could be used or combined in some manner:
Please describe your item in greater detail
Provide additional search terms for your item
Add more keywords to your item
Help us promote your item by adding more keywords
(this ties in nicely with the "The more richly you describe your work the better we can promote it." text)

Just my thoughts.
