### ISSUE TITLE
“Approve on Behalf” of list should be scoped to reviewers who have NOT already decided

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#415]
Do not allow sign-off-on-behalf-of behavior for reviewers who have _already_ signed off.
![415-signoff-on-behalf-scope](https://cloud.githubusercontent.com/assets/2133/6964680/6d462dfa-d919-11e4-8ab0-716f2ac0d167.png)

Bonus points for turning the form into a “panel” and adding [Bootstrap-compatible form classes](http://getbootstrap.com/css/#forms).

**Comment by jeremyf** [comment]
```
As the grad school reviewer that is signing off on behalf of other
people,
I want to only see a list of people that have not already sign off,
So that I don't end up signing off multiple times for the same person.
```
