### ISSUE TITLE
Incorporate Patent/Publication Information for ETDs

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#421]
In the [confirmation of grad school signoff email](https://github.com/ndlib/sipity/blob/4d919026b53d9c27141d7746bc9a4f651c7a1f69/app/views/sipity/mailers/email_notifier/confirmation_of_grad_school_signoff.html.erb) there is a placeholder for Patent/Plublication Information:

> ## Patent/Publication Information:
> * I have chosen to restrict or delay access to this ETD because: [Reason for restriction: ]
> * I attest that I have requested or received permission to include 3rd party materials in the document: [Copyright y/n]

This is information that we have not adequately captured, and will need to be captured. I believe that this will need to be another required form to fill out.

**Comment by jeremyf** [comment]
@cdeluca495 I believe this is something we need to reach out to Sheri about. Perhaps we can model it after the existing ETD system?

**Comment by cdeluca495** [comment]
With regard to Patent or proprietary information, in the current ETD system all that exists in the "Access Controls" is a radio button that indicates: Secure the entire work for patent and/or proprietary purposes.

It would seem that if a user is depositing patent or proprietary materials then they should select "Private" in the Sipity access controls.  Additionally, we could add a small amount of help text indicating the selection of "Private" where there are scenarios potentially involving such proprietary materials.
