### ISSUE TITLE
Truncate the Abstract to some acceptable amount of text

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#422]
As it stands now, the abstract field will accept any amount of text that is entered into it.  Ideally on the show page the abstract will be truncated to a reasonable amount of lines.  

See this work for an example of what it shouldn't be like.
https://sipity-staging.library.nd.edu/works/dev00099m9b

**Comment by jeremyf** [comment]
To consider: If we truncate the HTML, we will need to expose some means of seeing all of the abstract.

Proposal: Render the truncated and non-truncated HTML on the dom. By default the truncated HTML is hidden via CSS. Then, on page load JS would show the truncated HTML, hide the untruncated HTML, and append a "..." link that would allow viewing the truncated HTML (perhaps in a lightbox).

Thoughts? @danhorst
