### ISSUE TITLE
Change email subjects to align with email content

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#435]
Almost all the emails are sent with the same title:
`Sipity: Review #{WORK_TYPE} “#{WORK_TITLE}”`

This isn’t very helpful. The subject line should reflect the content of the message.

**Comment by banurekha** [comment]
@danhorst how do you want subject to be configured for each email? can we leverage I8n for email subject? Content of the email is through layout but subject is from work itself.

**Comment by jeremyf** [comment]
@banurekha I18n is a great option; I believe we could adjust the following:

```ruby
mail(options.slice(:to, :cc, :bcc).merge(subject: @entity.email_subject))
```

to something like:

```ruby
mail(options.slice(:to, :cc, :bcc).merge(subject: subject_for(email_name: method_name)))
```

Then define (in the mailer) a method for `subject_for`. It would need to use I18n (which may not be available in a mailer method). I don't believe that we will need the `email_subject` methods any more (which could be removed once adjustments were made to the notifier).
