### ISSUE TITLE
Clarify ControlledVocabulary column names and usage

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#465]
I'm finding the existing controlled vocabulary column names confusing:

```
Sipity::Models::SimpleControlledVocabulary.new(
  predicate_value: 'CC0 1.0 Universal',
  predicate_value_code: 'http://creativecommons.org/publicdomain/zero/1.0/'
)
```

I believe the current `predicate_value` should be `predicate_label` and the `predicate_value_code` should be `predicate_value`.

After all, we are going to persist the URI in Fedora. I have no idea how this relates to the controlled vocabulary for degree names. It would appear we are persisting different information.

Perhaps @dbrower could weigh in?

**Comment by dbrower** [comment]
yes, I agree `predicate_label` and `predicate_value` is clearer than what is currently there.

Usually in RDF _predicate_ refers to the linking relation between a _subject_ and an _object_. Maybe consider using `subject_label` and `subject_uri` or some such instead (e.g. `term_label` and `term_uri`)?

**Comment by jeremyf** [comment]
@dbrower We don't have URIs in each case, so I'm thinking predicate_label and predicate_value for an improvement of clarity. @banurekha added the predicate value code; It appears the codes are being used for lookup. Which means we are probably overloading those column values.
