### ISSUE TITLE
Missing Translation - translation missing: create.signoff_on_behalf_of_triggered

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#484]
When "signing off" on behalf of a committee member the translation is missing.

translation missing: en.sipity/work_event_triggers.action/create.signoff_on_behalf_of_triggered

**Comment by rbalekai** [comment]
Fixed by https://github.com/ndlib/sipity/commit/d63af009200c5268a074e2ae42aa8dd18b142d05
