### ISSUE TITLE
Intake form for new ULRA submissions

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#503]
Rather than having all Work Areas share a single deposit form, e.g. `/works/new`, each Work Area will have a tailored intake form.

The ULRA intake form should have four panels:

## What is the _title_ of your submission?
(This fieldset is the same as the one in `app/views/sipity/controllers/works/new.html.erb
`)
- **Title**, single attribute

## Who is the _primary faculty advisor_?
- **Advisor netID**; single attribue; must be a valid netID

## What _kind_ of submission is this?
- **Award category**, single attribute; radio button list:
  - Senior/Honors Thesis
  - 2000–4000 Level Papers
  - 10000 Level Papers

## Do you have _publishing_ plans?
(This fieldset is the same as the one in `app/views/sipity/controllers/works/new.html.erb
`)
- **Publication intent** single attribute; radio button list:
  - I have _no plans to publish_ this work in the future.
  - I have _already published portions_ of this work..
  - I am _planning on publishing_ this work in the future.
  - I don’t know.

The intake form should look like this:
![503-ulra-intake](https://cloud.githubusercontent.com/assets/2133/7187740/c7f287e4-e440-11e4-98ad-efc05de50304.png)

There is [a full list of the needed enrichments](https://docs.google.com/spreadsheets/d/1Lh2nnBK_sBw2QG0fth1ezVgAQyAcrWeJ0FOfIkv3Bgk/edit?usp=sharing) that will be addressed across several issues.

**Comment by jeremyf** [comment]
The form object should be:

`Sipity::Forms::Ulra::StartASubmissionForm` in `app/forms/sipity/forms/ulra/start_a_submission_form.rb`

The template should be in ERB (I don't think we'll ever give user facing control over form rendering). At present I don't know where the template should be.

**Comment by jeremyf** [comment]
You should be able to work on the final aspect of this.

At present, the form is not valid.
