### ISSUE TITLE
CreateWork should be a StrategyAction

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#506]
At present the CreateWork form is an implicit StategyAction that is allowed by anyone. It is something that needs to be narrowed in scope: either a group or role is allowed to take the action.

This is important as it relates to the emails sent out for #292.

**Comment by jeremyf** [comment]
We may not need to worry about the strategy action aspect because I'm looking to leverage entering and exiting states for email notification.

**Comment by cdeluca495** [comment]
What exactly is a strategy action?

**Comment by jeremyf** [comment]
Its one of the models in Sipity.

**Comment by jeremyf** [comment]
Relates to #507

**Comment by jeremyf** [comment]
This will be building from `Work Area` and `Submission Window`

**Comment by jeremyf** [comment]
This has been completed as part of #644 (@8f58da1)
