### ISSUE TITLE
Refactor Gemfile to have a deploy group

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#530]
Given how we are deploying via Capistrano (i.e. Jenkins installs all the bundles), I want to switch so that Jenkins only installs the bare bones for deployment. This would involve:
- creating a :deploy group in the Gemfile
- adding :deploy as the ignored groups as part of the deploy.rb (as they are analogous to development)
- adding a bundle imperative to the Jenkins task that ignores all but the :deploy group

**Comment by danhorst** [comment]
There are one or more gems that will no longer install under Ruby 2.0.x. Look in the Jenkins deployment logs to see which ones are failing.

Because Jenkins will not be running the entire application we only need to include the bare minimum of gems for Capistrano to execute a deployment.

**Comment by jeremyf** [comment]
It appears as though @banurekha has resolved the deploy with help from Mark. I'm going to move this to the Icebox.
