### ISSUE TITLE
What is the best way to trigger temporal changes?

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#560]
Submission Windows have time-based state changes. How should we go about solving this?
1. [Clockwork](https://github.com/tomykaira/clockwork) manages time-based triggering by running a separate application process.
2. [Minicron](https://github.com/jamesrwhite/minicron) and [Whenever](https://github.com/javan/whenever) wrap cron jobs.
3. Punt. Make it a manually-triggered process and just give them a button.

**Comment by dbrower** [comment]
Wrapping cron is easier than making sure a process stays running.

What kind of granularity is needed for temporal changes? If daily is good enough, we could install a cron job to run a rake task daily (say, 3 am).

**Comment by jeremyf** [comment]
For now, I'd like this to not track to the ULRA task; I believe we need not worry about any of the requirements not being something we can do by hand.

**Comment by jeremyf** [comment]
I've added the whenever gem @3da5e5c85371acff8521b7ef0b7be53c5ef69a7a
