### ISSUE TITLE
Not able to request_change_on_behalf_of

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#565]
Unable to request_change_on_behalf_of.  User is presented with this message and unable to submit the request for changes.
![2015-04-27_16-14-01](https://cloud.githubusercontent.com/assets/6973150/7356788/7a10dbaa-ecf8-11e4-9fdd-dd38e1594cd8.png)

**Comment by jeremyf** [comment]
This will need an 'on_behalf_of_collaborator' rendered with it.

**Comment by jeremyf** [comment]
Compare:

https://github.com/ndlib/sipity/blob/master/app/forms/sipity/forms/etd/request_change_on_behalf_of_form.rb#L33-L34

vs.

https://github.com/ndlib/sipity/blob/master/app/forms/sipity/forms/etd/signoff_on_behalf_of_form.rb#L29-L31

The broken form is requiring the on_behalf_of_collaborator_id but never rendering the input field.
