### ISSUE TITLE
Create the concept of :anyone_that_is_registered as a valid Role

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#582]
In this case, `everyone` would mean an authenticated user.

Given that we are leveraging the database to determine action availability, the concept of an `everyone` role needs to be available. I believe some of the queries will need to be short-circuited to say `OR sipity_roles.name = 'anyone_that_is_registered'`

**Comment by dbrower** [comment]
I don't like the label everyone. Maybe use "signed-in" or "registered" (a
la hydra).

Also, why ==? Shouldn't the roles of user be a list?

Also, is the concept of "no-one" useful? What about an actual "everyone"
everyone? (This comes from, we have a poset of roles why not add top and
bottom?)

On Tuesday, April 28, 2015, Jeremy Friesen <notifications@github.com> wrote:

> In this case, everyone would mean an authenticated user.
>
> Given that we are leveraging the database to determine action
> availability, the concept of an everyone role needs to be available. I
> believe some of the queries will need to be short-circuited to say OR
> sipity_roles.name == 'everyone'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndlib/sipity/issues/582>.
>


-- 

*Donald Brower, Ph.D.** Digital Infrastructure Lead*
* Hesburgh Libraries — Digital Library Initiatives and Scholarship*

*University of Notre Dame*
208 Hesburgh Library
Notre Dame, IN 46556
*o:* 574-631-1566
*e:* dbrower@nd.edu

**Comment by jeremyf** [comment]
I'm going with `anyone_that_is_registered`

**Comment by jeremyf** [comment]
I'm exploring the solution and have found the three queries that will need amendments. I'll be writing the expected output and working on the implementation from there.

**Comment by jeremyf** [comment]
And as I'm thinking more on this, the Role is the wrong thing. I believe there needs to be an "anyone_that_is_registered" actor.

**Comment by jeremyf** [comment]
Closed by #584
