### ISSUE TITLE
Sipity ETD to ROF bridge

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#598]
We need a way to serialize a ETD stored in Sipity to [ROF](https://github.com/ndlib/rof). This scope of this issue is to build the serializer. Integration testing from Sipity to ROF to CurateND will be the focus of another issue. Here are some of the identified tasks

- Reuse Curate-batch process to ingest work into curate (https://github.com/ndlib/curatend-batch)
- Map work attributes to ETD Model and add any descMetadata that might be missing or identified during mapping process
- Use mapper/converted to convert work and related entity to ROF format
- Use  exporter to bundle work, attachments and related metadata and move it to mounted samba directory (refer to curate-batch process manual for more details)
- Use background process and cron job to kick ingest process 
- Finally test the whole integration and rework on missing pieces if any.

**Comment by dbrower** [comment]
There is more than one way to serialize an ETD into ROF. What is the expected goal of the serialization?

**Comment by danhorst** [comment]
The goal is to use ROF to create a Fedora object that can be loaded by the ETD ActiveFedora model that already exists in CurateND.

**Comment by dbrower** [comment]
I ask since would make different suggestions depending on whether you intend to use the batch loading processing or not.

One way is for you to translate the ETD's into the low-level ROF yourself. Another way is to define a higher level ETD ROF object, and use that.

BTW, I am open to adding APIs to the batch loading process.

**Comment by danhorst** [comment]
@dbrower is correct. I was falsely conflating ROF and the batch ingest process. What I would like is to have Sipity use the batch ingest process to create AIPs that are then written to the preservation system.

That makes the scope of this ticket for Sipity to be able to represent objects in the JSON-LD format used by the batch ingest system.

**Comment by dbrower** [comment]
And, to be pedantic again, the ROF format is not JSON-LD itself, but it does use JSON-LD to encode the metadata section for items.

Again, since ROF is only really used internally, we have some latitude with defining and redefining it to do what we need it to do.

**Comment by jeremyf** [comment]
Closed via @462a1df
