### ISSUE TITLE
Any record that fails is then "locked" from ever being editable or useable or viewable.

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#662]

**Comment by jeremyf** [comment]
@cdeluca495 I need more context for this. What do you mean by "record that fails"?

**Comment by cdeluca495** [comment]
If a problem is encountered when accessing a record and an error is generated, any time a user tries to access that record, the record will not be available to any user and the same error will result.  I hope this helps.

**Comment by jeremyf** [comment]
I believe this has been fixed with: @c1c1e0a0ffb1abd18c59279422c915d9af35d8cb
