### ISSUE TITLE
Sipity - Grad_school_requests_changes

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#672]
Once an advisor(s) sign off on a students item, it goes to the grad school for review.  Once the Grad school requests changes to that item the student no longer has the ability to edit any of the todo items for the work even though the request may be to do so.

**Comment by jeremyf** [comment]
Once approved by the advisors, the Student can no longer make changes to the work.  Instead we need to expose an ability for the Grad School to edit the todo items.

**Comment by cdeluca495** [comment]
Maybe we haven't fully thought this through, but if the grad student cannot
make changes...what purpose does it serve to have the grad school request
that changes should be made?


*Chris DeLuca*
*Lead Digital Library QA Developer**Hesburgh Libraries*
*University of Notre Dame*
208 Hesburgh Library
Notre Dame, IN 46556
*o:* 574-631-1388
*e: *cdeluca1@nd.edu

**Comment by jeremyf** [comment]
Its matter of tracking state changes for the Grad School; so Shari knows
when something is not in her court.

On Thursday, June 4, 2015, Chris DeLuca <notifications@github.com> wrote:

> Maybe we haven't fully thought this through, but if the grad student cannot
> make changes...what purpose does it serve to have the grad school request
> that changes should be made?
>
>
> *Chris DeLuca*
> *Lead Digital Library QA Developer**Hesburgh Libraries*
> *University of Notre Dame*
> 208 Hesburgh Library
> Notre Dame, IN 46556
> *o:* 574-631-1388
> *e: *cdeluca1@nd.edu <javascript:_e(%7B%7D,'cvml','cdeluca1@nd.edu');>
>
> On Thu, Jun 4, 2015 at 4:33 PM, Jeremy Friesen <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Once approved by the advisors, the Student can no longer make changes to
> > the work. Instead we need to expose an ability for the Grad School to
> edit
> > the todo items.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ndlib/sipity/issues/672#issuecomment-109040404>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndlib/sipity/issues/672#issuecomment-109048327>.
>


-- 

Jeremy Friesen
takeonrules.com
