### ISSUE TITLE
Sipity Dashboard - Filter by date created

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#674]
Add a filtering mechanism to the dashboard so records may be sorted by "Date Created".

**Comment by jeremyf** [comment]
Alas, we have two Dashboards. The /areas/etd and the /dashboard

I've added the filter to /areas/etd but not /dashboard. Which reminds me, what should we do about the multiple dashboards?

**Comment by cdeluca495** [comment]
Perhaps we need to talk about not only what would appear on this dashboard
in terms of the various works across work areas, but also the expectations
of the dashboard as a whole.  For example, is the dashboard a place one
would go to create work areas?  Or does this make it seem like more of an
administrative component of the application rather than an informative
component?


*Chris DeLuca*
*Lead Digital Library QA Developer**Hesburgh Libraries*
*University of Notre Dame*
208 Hesburgh Library
Notre Dame, IN 46556
*o:* 574-631-1388
*e: *cdeluca1@nd.edu
