### ISSUE TITLE
Sipity ETD - Publication and Patent information is optional on todo items

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#675]
The publication and patent information is on the initial work creation screen AND it is an optional to do item.  It should not be an optional to do item.

**Comment by jeremyf** [comment]
I disagree that this is a bug. The TODO item is optional; Meaning it need not be completed; It has already been completed. Perhaps the more appropriate thing to do would be to "auto-complete" the task on creation.

That is a bigger issue to resolve.

**Comment by jeremyf** [comment]
@cdeluca495 The proposed solution:

1) Make this a Required TODO item
2) Put it at the front of the list (will that break your tests?)
3) When the work is created, mark the TODO item for Publication and Patenting as done

Is that reasonable?

**Comment by cdeluca495** [comment]
Yes, all of that is reasonable.


*Chris DeLuca*
*Lead Digital Library QA Developer**Hesburgh Libraries*
*University of Notre Dame*
208 Hesburgh Library
Notre Dame, IN 46556
*o:* 574-631-1388
*e: *cdeluca1@nd.edu
