### ISSUE TITLE
Change language for Add Collaborators button

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#700]
Feedback heard during UAT was that "Add" was not helpful or intuitive.  Change "add" to "Add another Advisor"

![2015-06-09_20-51-36](https://cloud.githubusercontent.com/assets/6973150/8072821/d6ea7580-0ee9-11e5-9a3c-fc62c6cc9a48.png)

**Comment by jeremyf** [comment]
Per discussion, going with "Add another Person"
