### ISSUE TITLE
Sipity - Defense Date Validation

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#703]
If a defense date is chosen for a date in a month that doesn't have that day, for example september 31st, an error is given to the user that the value cannot be blank and the date field resets back to the default defense date.  It's almost as if the date field is now performing date validation for months that don't have all 31 days.  If that's the case then it's ok, we could just change the translation message to indicate "that day doesn't exist in that month" or something like that.
![2015-06-09_21-16-04](https://cloud.githubusercontent.com/assets/6973150/8073037/9dc4400c-0eed-11e5-968e-8330fff3e4ee.png)

**Comment by danhorst** [comment]
It would be simplest if the validation message could be the same for both cases:
1. No date was selected
2. An invalid date was selected

How about: “select a valid date” instead of “can't be blank”

Any wordsmithing @cdeluca495?

**Comment by jeremyf** [comment]
@danhorst that is the quickest change
