### ISSUE TITLE
Date controller on access_policy page prompts user for date on Open Access

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#721]
This may be related to a change that was made for the defense date, but if a user has a work/ file that is open access, on the access_policy page the user is prompted for an embargo date.  Previously, todays date was defaulted in this field.  The default date was removed as part of the change for the defense date changes. https://github.com/ndlib/sipity/issues/703
![2015-06-12_08-03-43](https://cloud.githubusercontent.com/assets/6973150/8129707/df0749c2-10d9-11e5-9d03-02eeffb64e00.png)

**Comment by jeremyf** [comment]
Closed via @b1c198db719434a4c0915010049fce6d1dc9ed04
