### ISSUE TITLE
Dashboard search criteria should be paginated

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#729]
The various dashboards should be paginated. Otherwise things are going to explode in a noisy mess.

**Comment by cdeluca495** [comment]
Agreed.  What do you think, 20 or 25 items per page seems reasonable.


*Chris DeLuca*
*Lead Digital Library QA Developer**Hesburgh Libraries*
*University of Notre Dame*
208 Hesburgh Library
Notre Dame, IN 46556
*o:* 574-631-1388
*e: *cdeluca1@nd.edu

**Comment by dbrower** [comment]
In other dashboards I've seen the number of items is selectable by the user, with a default of 20 or so.
