### ISSUE TITLE
Remove apostrophe in the "View Submitted ETD's button

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#739]
On the ETD work area dashboard, remove the apostrophe in the view submitted etd's button.
https://sipity-staging.library.nd.edu/areas/etd

 href="https://curate.nd.edu/catalog?utf8=%E2%9C%93&amp;search_field=all_fields&amp;q=etd" class="btn btn-primary">View Submitted ETD's

**Comment by jeremyf** [comment]
Done via @697d5c63

Requires deploy to staging.
