### ISSUE TITLE
ETD - Sipity - Collaborators Review box doesn't render full values in IE

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#766]
In IE, the Yes/No dropdown field renders poorly. Please make it slightly wider so it renders properly.
This field renders fine in every other browser(as expected ;) .

![2015-06-18_10-00-04](https://cloud.githubusercontent.com/assets/6973150/8232873/d0669492-15a0-11e5-8132-cb98aeaf2b5a.png)

**Comment by jeremyf** [comment]
Replaced with checkbox instead of dropdown.
