### ISSUE TITLE
Access Controls Page - Copyright Information - Add informational link

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#776]
On the access controls page add a sentence and a link under the copyright option so that users can look up different copyright information.

"For more information on copyright options please see this link."

and the link should redirect to http://www.nd.edu/copyright/
![2015-06-18_16-07-41](https://cloud.githubusercontent.com/assets/6973150/8240935/3a539142-15d4-11e5-8a91-f7bd0107c995.png)

**Comment by jeremyf** [comment]
It is easiest to put the hint below the select box (and we can better ensure that all copyright inputs have that text).
