### ISSUE TITLE
Sipity - Missing Translation - UNDER_GRAD_SCHOOL_REVIEW_WITH_CHANGES 

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#777]
When changes have been made to the work at the request of the grad school, the translation is missing.  See screenshot.
![2015-06-18_18-12-57](https://cloud.githubusercontent.com/assets/6973150/8243551/f41ecec8-15e5-11e5-8f1f-3c0096f56d4e.png)

See example work:
https://sipity-staging.library.nd.edu/work_submissions/dev00124n3q

**Comment by jeremyf** [comment]
Related to #773, will be closed when #775 is merged
