### ISSUE TITLE
Add Grad School Support information to footer

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#778]
From Shari:
If it's possible, it might be good to add a line of text to the footer or somewhere on each screen:  "If you have questions about this site or about the formal submission process, please contact the Graduate School's dissertation editor at dteditor@nd.edu or 574-631-7545." 

There should be a small discussion about this.  Currently the footer mentions contacting curateND tech support with any concerns.  Who will be responsible for maintaining each of the different work areas?  CurateND Support?

**Comment by jeremyf** [comment]
I'm going to add a work area footer rendering option to the template.
