### ISSUE TITLE
Collaborators Involved: Language changes needed to address user confusion

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#788]
Somewhere on the Collaborators involved page, this text needs to be added in order to clear up confusion on behalf of the students:

"Request for approval emails will only be sent to Research Directors who are added by NetID. If you have a co-director who does not have a NetID, please add them by email and ask them to contact dteditor@nd.edu to approve this work for submission to the Graduate School. Once we have their permission, the Graduate School editor will sign-off on their behalf."

**Comment by jeremyf** [comment]
We can send the collaborator emails as well; Just need to mark that as a requirement.

**Comment by jeremyf** [comment]
(Accidentally clicked close and comment)

**Comment by cdeluca495** [comment]
The user would not have a netID(presumably) so they would still need to
contact Shari to have her sign off on the record.  Perhaps if an email is
sent to NonND collaborators the email just needs language explaining the
process for Shari sign off on their behalf.


*Chris DeLuca*
*Lead Digital Library QA Developer**Hesburgh Libraries*
*University of Notre Dame*
208 Hesburgh Library
Notre Dame, IN 46556
*o:* 574-631-1388
*e: *cdeluca1@nd.edu

**Comment by jeremyf** [comment]
I cannot click the right button.

**Comment by cdeluca495** [comment]
Shari has approved sending the email to the nonND email address.  Here is the text to add to the email:

[Student name] has begun the formal electronic submission process for a [doc type], and has identified you as a primary research director or advisor for this document. As part of the formal submission, the Graduate School requires your approval before the submission can move forward for our review.

To review and approve this [doc type] for formal submission to the Graduate School, you may either:

Use your active, personal NetID and password to go directly to this student’s submission; or 
If you have previously reviewed the final version of the document, provide your student with two copies of the printed title page with your original signature.
If you have questions about this process, do not currently have a NetID, or are unable to complete either of these approval options, please email me at shill2@nd.edu or call 574-631-7545 for assistance.

Regards,

Shari Hill Sweet
Dissertation and Thesis Editor
Graduate School
502 Main Building
Notre Dame, IN 46556

**Comment by banurekha** [comment]
Here are my finding when researched on how to handle this with Jeremy Help

Here is my details finding of if I can have query for non-nd collaborators in data driven formate

 For every collaborators
   * Creates collaborators 
   * Then create User who have net_id (nd user, /app/repositories/sipity/commands/work_commands.rb:27)
   * And for those users, 
           ** change_processing_actor_proxy (/app/repositories/sipity/commands/work_commands.rb:29), Non-nd user have nd user as their proxy
           ** repository.grant_permission_for!(actors: user, entity: work, acting_as: Models::Role::ADVISOR) (/app/repositories/sipity/commands/permission_commands.rb:22)
                   - This responsible for creating  entity specfic responsibility (/app/services/sipity/services/grant_processing_permission.rb:20) and happens only for nd user

So from above finding, even though we have  to_processing_actor (/app/models/sipity/models/collaborator.rb:24)

I don't think proper data points are not created (meaning, processing actor or responsibility or related to any role) for non-nd user so we can't have query as we expected
so query that relates with Collaborator -> Processing Actor -> (StrategyResponsibility || EntityResponsibility) -> StrategyRole -> Role is not possible

I think it is getting overly complicated (at least for me, so let me know your thought if we could do this feature later and do some assumption)

Also More finding from Jeremy and his thoughts on this process

I believe when we create a Collaborator we need to also create the corresponding processing actor. If memory served, I was thinking to delay that decision regarding the processing actor. However I believe we can make sure that we have one for collaborators.

app/repositories/sipity/commands/work_commands.rb:26

I believe the following change might help create the processing actors at the right point in time. However, these changes result in more chatter on the wire. Perhaps a service class should be extracted to better encapsulate the logic?

```ruby
next unless collaborator.responsible_for_review?
collaborator.to_processing_actor
create_sipity_user_from(netid: collaborator.netid, email: collaborator.email) do |user|
  change_processing_actor_proxy(from_proxy: collaborator, to_proxy: user)
end
repository.grant_permission_for!(actors: collaborator, entity: work, acting_as: Models::Role::ADVISOR)
```

Also, this work may not be as vital, once we get Cogitate in place. Dan and I talked about allowing an email to be a permanent durable identifier that we could use as a key for the processing actor.

**Comment by dbrower** [comment]
This makes my head hurt.

Jeremy and I made a distinction between how emails would be used in Cogitate. They could be used as unique identifiers, they can also be used as a communication channel. So there would be fields in cogitate for both `identifier` which could be an email address, and `primary_email` which is for communication.
