### ISSUE TITLE
Missing Translation: works.processing_state.under_grad_school_review_with_changes.can_advance

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#805]
Any record in Under Grad school review with changes will display a missing translation.  Please remove.
![2015-06-30_15-06-04](https://cloud.githubusercontent.com/assets/6973150/8439361/909c2370-1f39-11e5-8650-001e3754f10c.png)

**Comment by jeremyf** [comment]
This is related to #807; In that we need to revisit what the state machine actually is.
