### ISSUE TITLE
Painfully slow render times

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#806]
The following template is rendering very slowly: `sipity/controllers/work_submissions/etd/attach.html.erb`

```console
Started GET "/work_submissions/2514nk33x76/do/attach" for 10.38.67.55 at 2015-07-01 15:38:07 -0400
Processing by Sipity::Controllers::WorkSubmissionsController#query_action as HTML
Parameters: {"work_id"=>"2514nk33x76", "processing_action_name"=>"attach"}
```

There is one attachment, with size 1.6MB.

**Comment by jeremyf** [comment]
Based on our work, it appears that generation of thumbnails for non-images is causing the pain.

**Comment by danhorst** [comment]
Thumbnail generation can be turned off for the time being. It is causing an unacceptable delay in the ETD reviewer workflow.

We should try to solve the thumbnail caching problem before Sipity replaces the CurateND self-deposit system.

**Comment by jeremyf** [comment]
Can we get a 64x64 "attachment" icon?

Images do not appear to be slow on thumbnails, so I assume its something to do with `file.name` being called.

```ruby
def thumbnail_url(width: THUMBNAIL_WIDTH, height: THUMBNAIL_HEIGHT)
  if file.image?
    file.thumb("#{width}x#{height}#").url
  else
    extname = File.extname(file.name).sub(/^\./, '') + '.png'
    File.join(Dragonfly.app.server.url_host, 'extname_thumbnails', width, height, extname)
  end
end
```

https://github.com/ndlib/sipity/blob/54168c09c3623acf41b4b1c4d4d22ee221e9f3e1/app/models/sipity/models/attachment.rb#L23-L30

**Comment by jeremyf** [comment]
It appears that `file.image?` is the culprit.

**Comment by jeremyf** [comment]
See #812
