### ISSUE TITLE
Allow for more flexibility in embargo enforcement

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#821]
@dbrower suggested that we allow for more nuance in embargo enforcement. There are two cases we should accommodate:
1. Embargo _both_ the metadata and the files; there will be no public acknowledgement that the work exists until the embargo date has passed.
2. Allow the metadata to be public but embargo the files; the work will be discoverable via the abstract and other metadata but the extent of the work will be repressed until after the embargo date has passed.

This will require altering the access control questions as well as how the permissions will map to the preservation system.

**Comment by dbrower** [comment]
This is only a suggestion to take the distinction between a work and its files into account. I handled a support issue this morning where someone couldn't find an ETD because it was embargoed on the metadata level. If only the files were embargoed, the ETD would have been at least discoverable.

**Comment by jeremyf** [comment]
At present, the Sipity system does differentiate between the access controls of the work and the files.
