### ISSUE TITLE
Can not delete collaborator

### ISSUE THREAD

**Issue by rbalekai** [ndlib/sipity#828]
Steps to reproduce:

Add collaborator-A and set role as "Research Director"
Save the Changes
Goto Edit Collaborator
Add collaborator-B and set role as "Research Director"
Remove collaborator-A and save the changes
Goto Edit Collaborator
collaborator-A still exists

**Comment by jeremyf** [comment]
![repository_deposit_interface](https://cloud.githubusercontent.com/assets/2130/8551927/b5979bbe-24a7-11e5-8d2c-f9bbe1182ea8.png)
