### ISSUE TITLE
Display the repository URL during cataloging

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#850]
```gherkin
Given I am in the cataloging group
When I view an item in the "ready for cataloging" state
Then I will see what the URL will be when it is deposited in CurateND
```
The URL should follow the pattern:
```
https://curate.nd.edu/show/:pid
```
It should be displayed in the “overview”

![850-display-repository-url](https://cloud.githubusercontent.com/assets/2133/8755351/33d30bce-2c98-11e5-8dfb-62112e7fabbb.png)

**Comment by banurekha** [comment]
Curate url is only visible to cataloging group? is there a role/group for cataloging in sipity?

**Comment by danhorst** [comment]
The URL will be correct as soon as the PID for the item in Sipity is minted. The URL will not _resolve_ correctly until after the item has been ingested into the repository. (We have talked about having a landing page for PIDs that have been minted but do not have a repository record but that is out of scope.)

Restricting the URL to cataloging group is optional but not required.
