### ISSUE TITLE
Perform an import of approved ETDs into CurateND

### ISSUE THREAD

**Issue by danhorst** [ndlib/sipity#874]
After the cataloging workflow states have been created and made available, #802, ETDs that are “ready for cataloging” can be imported into CurateND.

The graduate school has been getting questions about _when_ ETDs will be “live” in CurateND. Because ETD submissions go through a rigorous review process RAD signoff doesn’t _have_ to block the submission of an ETD to CurateND.

Importing ETDs into CurateND without first having a cataloging review is a temporary measure. As long as the ETD import process _updates_ existing ETDs it can safely be run a second time _after_ the record has passed through cataloging review.

---

This will have to accommodate the needs outlined in [ETD Cataloging and Ingest Changes](https://github.com/ndlib/sipity/blob/master/architecture/etd-cataloging-and-ingest.md).

**Comment by dbrower** [comment]
Will the ETDs still be cataloged and put into Aleph?

Aleph is the route the previous ETDs took to be put into Primo. If we don't maintain consistency with that then it will make indexing curate into Primo *much* harder since some ETDs will be indexed by their aleph records, and some won't be.

**Comment by danhorst** [comment]
Yes, RAD will still perform original cataloging on ETDs and imoprt the OCLC records into ALEPH. 

However, that process does not need to block the import of August graduation (and possibly December) ETDs from being imported into CurateND. Several other development initiatives have been pushed ahead of implementing the cataloging workflow in Sipity and I do not want the data to be stuck in limbo.

**Comment by jeremyf** [comment]
This has been completed and running regularly.
