### ISSUE TITLE
Validate the date field on the Postponed cataloging page

### ISSUE THREAD

**Issue by cdeluca495** [ndlib/sipity#897]
The date field needs to have validation on it for any user.  Even though it was understood by Shari that the format would be mm/dd/yyyy there  may be student workers performing these actions and they may not understand the format. Also add some type of hint text indicating the preferred format for date entry.
![2015-10-07_15-51-10](https://cloud.githubusercontent.com/assets/6973150/10349190/43f3198c-6d0b-11e5-8de0-d15ab01d468f.png)

**Comment by jeremyf** [comment]
Date is allowed to be nil. If its not nil, then it must be a valid date.
We don't need the I Agree.

**Comment by dbrower** [comment]
The label "Scheduled time" should probably read "Scheduled Date".
