### ISSUE TITLE
ULRA - Ingest Submission Objects

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#971]
Based on the Award Category, we will map the ULRA work to either a ETD or a Senior Thesis.

- [x] Map ULRA work predicates to ROF predicates
- [x] Attach files, ensuring that we don't attach the letter of recommendation from the faculty member
- [x] Create workflow actions and permission for Ingest that are analogue to ETD's workflow
- [x] Create a bulk ingest script analogue to https://github.com/ndlib/sipity/blob/master/app/jobs/sipity/jobs/etd/bulk_ingest_job.rb
- [x] Create a perform action for work https://github.com/ndlib/sipity/blob/master/app/jobs/sipity/jobs/etd/perform_action_for_work_job.rb
- [x] Create a `submit_for_ingest_form` analogue to https://github.com/ndlib/sipity/blob/master/app/forms/sipity/forms/work_submissions/etd/submit_for_ingest_form.rb
- [x] Create a `ingest_completed_form` analogue to
https://github.com/ndlib/sipity/blob/master/app/forms/sipity/forms/work_submissions/etd/ingest_completed_form.rb

**Comment by danhorst** [comment]
@jeremyf I’m starting work on `BatchIngestExporter::DirectoryMover`
